# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestfrhemsida():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testfrhemsida(self):
    self.driver.get("https://ntig-uppsala.github.io/Frisor-Saxe/")
    assert self.driver.find_element(By.CSS_SELECTOR, "header").text == "Frisör Saxé"
    assert self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(1) > h1").text == "Öppettider"
    assert self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(1) > h2").text == "Mån-Fre: 10-16\\\\nLördag: 12-15\\\\nSöndag: Stängt!"
    assert self.driver.find_element(By.CSS_SELECTOR, ".open > div:nth-child(2) > h1").text == "Adress"
    assert self.driver.find_element(By.CSS_SELECTOR, ".open > div:nth-child(2) > h2").text == "Fjällgatan 32H\\\\n981 39, Kiruna"
    assert self.driver.find_element(By.CSS_SELECTOR, ".tele-mail div:nth-child(1) > h1").text == "Telefonnummer"
    assert self.driver.find_element(By.CSS_SELECTOR, ".tele-mail div:nth-child(1) > h2").text == "0630-555-555"
    assert self.driver.find_element(By.CSS_SELECTOR, ".tele-mail div:nth-child(2) > h1").text == "E-post"
    assert self.driver.find_element(By.CSS_SELECTOR, ".tele-mail div:nth-child(2) > h2").text == "info@ntig-uppsala.github.io"
    self.driver.find_element(By.CSS_SELECTOR, ".facebook").click()
    self.driver.find_element(By.CSS_SELECTOR, ".facebook").click()
    self.driver.find_element(By.CSS_SELECTOR, ".facebook").click()
    self.driver.find_element(By.CSS_SELECTOR, ".facebook").click()
    self.driver.find_element(By.CSS_SELECTOR, ".facebook").click()
  
