# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Tests():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_Tests(self):
    self.driver.get("https://ntig-uppsala.github.io/Frisor-Saxe/")
    assert self.driver.find_element(By.ID, "titel").text == "Frisör Saxé"
    elements = self.driver.find_elements(By.ID, "opentimes")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.ID, "adress")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.ID, "phonenr")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.ID, "email")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, ".fa-facebook").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fa-instagram").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fa-twitter").click()
